### ISSUE TITLE
Table first cell population

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#28]
Update the tables so cell [0,0] (first colum, first row) contains data.
http://webaim.org/standards/508/checklist#standardg
http://webaim.org/standards/508/checklist#standardh
* ###### Size 3

**Comment by m4ttb13** [comment]
After fixing the other (bigger) issues with Enhanced Switch - I've had a look at the issues with Table Header being empty. Seems like a none issue/harder to fix than its worth. New table rows (header or otherwise) auto create a checkbox. This checkbox obviously makes the header empty *head -> desk* so would require a check after creating to add some sort of text in just incase. Leaving on backlog for now as I believe its a none issue but someone else may think otherwise.

**Comment by m4ttb13** [comment]
Thoughts?

**Comment by woody9944** [comment]
Could potentially replace the checkbox in the header with plain text, such as simply 'selected'.

**Comment by djbuckley** [comment]
I tend to defer to the [material design spec](https://material.io/guidelines/components/data-tables.html#data-tables-interaction)
this is disabled always... which would mark it as pointless, so thats something that probably needs to go
not sure what background tagging you could do, but the spec docs indicate just a tick box, so whatever it is would have to be invisible
