### ISSUE TITLE
DatePicker be able to 'esc' to close

### ISSUE THREAD

**Issue by m4ttb13** [manchesergit/material-ui#48]
Currently cannot hit Esc to close the window (even when focus is on it)

**Comment by djbuckley** [comment]
https://github.com/callemall/material-ui/issues/35

**Comment by djbuckley** [comment]
this stops the date picker handling the escape key as a close request
```javascript
  requestClose(buttonClicked) {
    if (!buttonClicked && this.props.modal) {
```
> Dialog.js : line 274

if the dialog is set to modal then you can't break out with an escape
datepicker uses modal boxes unless the picker is inline
```javascript
   const modal = (container === 'inline' ? null : true);
```
> DatePickerDialog.js : line 159

>

**Comment by djbuckley** [comment]
UI guideline examples

- [Apple macOS human interface guidelines](https://developer.apple.com/macos/human-interface-guidelines/windows-and-views/dialogs/)
   - > Include a Cancel button that responds to the standard cancelation keyboard shortcuts. A Cancel button provides a clear, safe way out of a dialog and returns the computer to the state it was in before the dialog appeared. Make sure the keyboard shortcut Command-period and the Esc (Escape) key are mapped to the Cancel button.
- [Microsoft Windows Experience guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742499.aspx)
   - > Pressing the Esc key always closes an active dialog box. This is true for dialog boxes with Cancel or Close, and even if Cancel has been renamed to Close because the results can no longer be undone.
- [Smashing Magazine modal window web design](https://www.smashingmagazine.com/2009/05/modal-windows-in-modern-web-design/)
   - >EXIT STRATEGY: BUTTON, CLICK OUTSIDE WINDOW, ESCAPE KEY LINK
To improve functionality, always provide an exit button in an upper corner of the window. It is standard practice to use a simple circular button with an “x” graphic, which is clean and quite obvious for the user. In the lightbox shown below, you can clearly see the exit button.
- [Demo of dialogs in Material Design on AngularJS](https://material.angularjs.org/latest/demo/dialog)
